name: FutureNavigator
favicon: null
layout_spectrum: 0.88807966071181
typography_spectrum: 0.09601104143075645
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2739891523960978
  lightness: 0.008724035928025842
  saturation: 0.16660587769001722
  rhythmicContrast: 0.7185342493467033
purpose: []
