name: FutureNavigator
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d6d8'
    - '#121a27'
    - '#384356'
    - '#787974'
    - '#d06f2f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.16660587769001722
  rhythmicContrast: 0.7185342493467033
purpose: []
