name: FutureNavigator
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e1e8'
    - '#1c2d38'
    - '#c8c1c8'
    - '#8aa07e'
    - '#716861'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.16660587769001722
  rhythmicContrast: 1
purpose: []
